<section class="container-fluid col-12">
    <header id="header">
        <a href="#">
            <img class="logo" src="../img/logo_galo.svg" alt="Logo Atletico Mineiro">
        </a>
        <nav id="navigation">
            <ul>

                <li><a href="#">História</a></li>
                <li><a href="#">Jogadores</a></li>
                <li><a href="#">Titulos</a></li>
                <li><a href="#">Destaques</a></li>

            </ul>

        </nav>
        <a href="/sair" class="btn-entrar"> Sair</a>
    </header>

    <section class="container-fluid ">
        <div class="row">
            <div class="d-flex justify-content-center ">

            <form method="POST" action="/cadastrarNoticia" class="col-12 ">
                    <h1 class="texto d-flex justify-content-center">Cadastrar notícias</h1><br>
                    <div id="forms" class="col-12 ">
                        <div class="mb-4 row col-6 mt-5 form-1">
                            <label for="titulo" class="col-sm-2 col-form-label">Titulo</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="titulo" id="titulo">
                            </div>
                        </div>
                        <div class="mb-4 row col-6 mt-2 form-2">
                            <label for="resumo" class="col-sm-2 col-form-label">Resumo</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="resumo" id="resumo">
                            </div>
                        </div>
                        <div class="mb-4 row col-6 mt-2 form-2">
                            <label for="imagem" class="col-sm-2 col-form-label">Caminho imagem</label>
                            <div class="col-sm-10">
                                <input type="text" name="imagem" class="form-control" id="imagem">
                            </div>
                        </div>
                        <div class="mb-4 row col-6 mt-5 form-1">
                            <label for="autor" class="col-sm-2 col-form-label">Jornalista</label>
                            <div class="col-sm-10">
                                <input type="text" name="autor" class="form-control" id="autor">
                            </div>
                        </div>
                        <div class="mb-3 col-6">
                            <label for="texto" class="form-label">Texto Notícia</label>
                            <textarea class="form-control" name="texto" id="texto" rows="8"></textarea>
                        </div>

                        <button id="botao" class="btn btn-warning btn-lg botao">Cadastrar</button>
                    </div>
                 </form>

                 <div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Save changes</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
            </div>
        </div>
        </div>
    </section>



    <footer id="footer" class="mt-3 col-12">
        <p class="text-footer"> &copy LOREM IPSUN DOLOR SIT AMET</p>
    </footer>
</section>