<section class="container-fluid col-12">
    <header id="header">
        <a href="#">
            <img class="logo" src="../img/logo_galo.svg" alt="Logo Atletico Mineiro">
        </a>
        <nav id="navigation">
            <ul>

                <li><a href="/home_adm">Home</a></li>
                <li><a href="#">Jogadores</a></li>
                <li><a href="#">Titulos</a></li>
                <li><a href="#">Destaques</a></li>

            </ul>

        </nav>
        <a href="/sair" class="btn-entrar"> Sair</a>
    </header>

    <section class="container-fluid col-12 ">
      
            <div class="d-flex justify-content-center col-12 ">

            <form method="POST" action="/cadastrarNoticia" class="col-12 ">
                    <h1 class="texto d-flex justify-content-center">Cadastrar notícias</h1><br>
                    <div id="forms" class="col-12 ">
                        <div class="mb-4 row col-6 mt-5 form-1">
                            <label for="titulo" class="col-sm-2 col-form-label">Titulo</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="titulo" id="titulo">
                            </div>
                        </div>
                        <div class="mb-4 row col-6 mt-2 form-2">
                            <label for="resumo" class="col-sm-2 col-form-label">Resumo</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="resumo" id="resumo">
                            </div>
                        </div>
                        <div class="mb-4 row col-6 mt-2 form-2">
                            <label for="imagem" class="col-sm-2 col-form-label">Caminho imagem</label>
                            <div class="col-sm-10">
                                <input type="text" name="imagem" class="form-control" id="imagem">
                            </div>
                        </div>
                      
                        <div class="mb-3 col-12">
                         <h3>Notícia</h3><br><br>
                            <textarea class="form-control" name="texto" id="texto" rows="8"></textarea>
                        </div>

                        <button id="botao" class="btn btn-warning btn-lg botao">Cadastrar</button>
                    </div>
                 </form>

     
            </div>
     
        </div>
    </section>



    <footer id="footer" class="mt-3 col-12">
        <p class="text-footer"> &copy LOREM IPSUN DOLOR SIT AMET</p>
    </footer>
</section>