<section id="container">
            <header id="header">
                <a href="#">
                    <img class="logo" src="../img/logo_galo.svg" alt="Logo Atletico Mineiro">
                </a>
                <nav id="navigation">
                    <ul>
                        
                        <li><a href="#">História</a></li>
                        <li><a href="#">Jogadores</a></li>
                        <li><a href="#">Titulos</a></li>
                        <li><a href="#">Destaques</a></li>
                        
                    </ul>

                </nav>
                <a href="/sair" class="btn-entrar"> Sair</a>
            </header>

            <section class="container col-12">
               <div class="row"> 
                   <h1>Cadastro de notícias</h1>
                    <div class="marcador">
                        <form action="">
                        <div class="mb-3 row">
                            <label for="inputPassword" class="col-sm-2 col-form-label">Titulo da notícia</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputPassword">
                        </div>
                </div>
                        </form> 
                    </div>
               </div>
            </section>

           

           <!-- <footer id="footer">

               <p class="text-footer"> &copy LOREM IPSUN DOLOR SIT AMET</p>
               -->
    </section>


