<section class="col-12">
<header id="header">
        <a href="#"> 
            <img class="logo" src="../img/logo_galo.svg" alt="Logo Atletico Mineiro">
        </a>
        <nav id="navigation">
            <ul>
            
            <li><a href="/home">Home</a></li>
            <li><a href="/listar_noticias">Listar Notícias</a></li>
            <li><a href="#">Gerenciar Jornalistas</a></li>
 
            </ul>

        </nav>
        <a href="/sair" class="btn-entrar"> Sair</a>
    </header>

<?php 
if(isset($_GET['error']) == 'id'){
?>
    <div id="error" class="col-12  ">
        <div class="alert alert-danger d-flex justify-content-center" role="alert">
            Não é Possível acessar esse ID
        </div>
    </div>
<?php } ?>
   
    
     
<div class="container-fluid col-12 margin mt-bottom-3">
<div class="card-body p-0 col-md-8" style="margin:0 auto">
    <div style="float:right">
        <a href="/CadNoticiaJornalista"><button class="btn btn-success">Adicionar</button></a>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th style="width:80%"><strong>Titulo</strong></th>
            <th style="width:20%"><strong>Ação</strong></th>
        </tr>
        </thead>
        <tbody>
            <tbody>
                
             <?php foreach($this->view->noticias as $indice => $noticia){?>
                <tr>
                     
                    <td><?= $noticia['titulo'] ?> </td>
                    <td style="display:flex;">
                        <a href="/alterarNoticiaJornalista?id=<?=$noticia['id'] ?>"><button class="btn btn-primary">Editar</button></a>
                        <form action="#" method="POST" style="margin-left:15px">

                        <button type="submit" class="btn btn-danger" style="float:right">Deletar</button>
                        </form>
                    </td>
                <tr>
                <?php } ?>
       
        </tbody>
    </table>
</div>

</div>


<footer id="footer" class="col-12 ">
        <p class="text-footer"> &copy LOREM IPSUN DOLOR SIT AMET</p>
</footer>

</section>

