<section class="container">
<div class="card-body p-0 col-md-8" style="margin:0 auto">
<div style="float:right">
    <a href="/listar_noticias_adm?acao=id"><button class="btn btn-success">Adicionar</button></a>
</div>
    <table class="table">
        <thead>
        <tr>
            <th style="width:80%">Numero</th>
            <th style="width:20%">Ação</th>
        </tr>
        </thead>
        <tbody>
            <tbody>
             
                <tr>
                    <td> {{ $numero->numero }} </td>
                    <td style="display:flex;">
                        <a href="/numeros/show/{{$numero->id}}"><button class="btn btn-primary">Editar</button></a>
                        <form action="/numeros/delete/{{$numero->id}}" method="POST" style="margin-left:15px">
                       
                        <button type="submit" class="btn btn-danger" style="float:right">Deletar</button>
                        </form>
                    </td>
                <tr>
       
        </tbody>
    </table>
</div>
</section>