      <?php 
        use App\Views\index\url;
      ?>

        <header>
            <nav class="navbar">
                <img src="../img/logo_galo.svg" class="logo" alt="Logo">
                <ul>
                    <li class="header_link"><a href="">Historia</a></li>
                    <li class="header_link"><a href="">Titulos</a></li>
                    <li class="header_link"><a href="">Sobre Nós</a></li>
                    <li class="header_link"><a href="">Noticias</a></li>
                </ul>

                <a href="/login" class="botao-login"> <span></span> Entrar</a>
            </nav>
        </header>
    <main>
        <section class="container">

        
        </section>
        
    </main>
    <footer class=""></footer>
      