      <?php 
        use App\Views\index\url;
      ?>

    <main>
        <section class="container">

        <header>
            <nav class="navbar">
                <ul>
                    <li><a href=""></a></li>
                    <li><a href=""></a></li>
                    <li><a href=""></a></li>
                    <li><a href=""></a></li>
                </ul>
            </nav>
        </header>
        </section>
        
    </main>
    <footer class="footer"></footer>
      