<section id="container">
            <header id="header">
                <a href="#">
                    <img class="logo" src="../img/logo_galo.svg" alt="Logo Atletico Mineiro">
                </a>
                <nav id="navigation">
                    <ul>
                        
                        <li><a href="#">HOME</a></li>
                        <li><a href="#">ADM</a></li>
                        <li><a href="#">Gerenciar usuarios </a></li>
                        <li><a href="#">HOME</a></li>
                        
                    </ul>

                </nav> 
                <a href="/sair" class="btn-entrar"> Sair</a>
            </header>

            <article id="article">
                <div class="box">
                    <a href="#" class="titulo"><p class="txt1">LOREM IPSUN DOLOR SIT AMET</p></a>
                  
                    <a href="#"><img src="../img/img1.jpg" alt="Imagem do Escudo do galos"></a>
                </div>
                <div class="box">
                    <a href="#" class="titulo"><p class="txt1">CONSTRUÇÃO DO ESTÁDIO</p></a>
                   
                  
                    <a href="#"><img src="../img/estadio.png" alt="Imagem do Escudo do galos"></a>
                </div>
                <div class="box">
                    <a href="#" class="titulo"> <p class="txt1">LOREM IPSUN DOLOR SIT AMET</p></a>
                  
                    <a href="#"><img src="../img/escudo.png" alt="Imagem do Escudo do galos"></a>

                </div>
                <div class="box">
                    <a href="#" class="titulo"><p class="txt1">LOREM IPSUN DOLOR SIT AMET</p></a>
                  
                    <a href="#"><img src="../img/finans.jpg" alt="Imagem do Escudo do galos"></a>

                </div>
               <div class="box">
                <a href="#" class="titulo"><p class="txt1">LOREM IPSUN DOLOR SIT AMET</p></a>
                  
                <a href="#"><img src="../img/finans.jpg" alt="Imagem do Escudo do galos"></a>

               </div>
                <div class="box">
                    <a href="#" class="titulo"><p class="txt1">LOREM IPSUN DOLOR SIT AMET</p></a>
                  
                    <a href="#"><img src="../img/finans.jpg" alt="Imagem do Escudo do galos"></a>

                </div>
                </article>

            </section>

            <footer id="footer">

               <p class="text-footer"> &copy LOREM IPSUN DOLOR SIT AMET</p>
               
            </footer>
    </section>