<section  class="marcador col-sm-12">
            <header id="header">  
                <a href="#"> 
                    <img class="logo" src="../img/logo_galo.svg" alt="Logo Atletico Mineiro">
                </a>
                <nav id="navigation"> 
                    <ul> 
                        <li><a href="/home">Home</a></li>
                        <li><a href="/CadNoticiaJornalista">Cadastrar Notícias</a></li>
                        <li><a href="/listar_noticias">Listar Notícias</a></li>
                    </ul>

                </nav> 
                <a href="/sair" class="btn-entrar"> Sair</a>
            </header>

            <h1 class="title-home"> Nóticias do Clube Atletíco Mineiro</h1>

                <?php

                foreach($this->view->home as $indice => $value){
                   
                ?>
                <article id="article" class="col-8 mt-5">
                    <div class="row">
                        <div class="box-img img-fluid">
                            <a href="#"><img src="../<?= $value['imagem'] ?>" alt="Imagem do Escudo do galos" class="img"></a>
                        </div>
                    </div>
                    
                    <div class="col-6  text-resume">
                        <a href="" class="link-text"><p class="text "><?= $value['resumo'] ?></p></a>
                    </div> 
                        
                </article> 
                <hr>
            <?php } ?>
 
          
    </section>
    
   <!-- <footer id="footer" class="col-12">
                <p class="text-footer"> &copy LOREM IPSUN DOLOR SIT AMET</p>
    </footer>-->
 
  
            
  
   


