        <!--<section class="notification">
            <p class="text-danger">ERRO: usuário ou senha invalidos!</p>
        </section>-->
       

    <section id="container-login">

        <img class="logo-login" src="img/logo_galo.svg" alt="Logo Atletico Mineiro">
        <form  method="POST" action="/autenticar">
            <div id="caixa-form">
                 <label>E-Mail: </label><input type="text" name="email" id="email"><br>
                 <label>Senha:</label>&nbsp;<input type="password" name="senha" id="senha">
            </div>
            <button class="btn-login"  >Entrar</button><br><br>

           
        </form>
     </section>
     
